In [53]:
# Importing the necessary libraries

# Importing data with pandas
import pandas as pd

# Importing numpy to handle numpy data
import numpy as np

# Importing the convenient module train_test_split for data splitting
from sklearn.model_selection import train_test_split

# Importing the library for undersampling
#from imblearn.under_sampling import RandomUnderSampler

# Importing the module for data standardization
from sklearn.preprocessing import StandardScaler

# Importing the module for logistic regression
from sklearn.linear_model import LogisticRegression

# Importing the module for drawing histograms
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the module for creating accuracy scores
from sklearn.metrics import accuracy_score

# Importing the module for creating confusion matrices
from sklearn.metrics import confusion_matrix

# Importing the module for creating ROC curves
from sklearn.metrics import roc_curve
from sklearn.metrics import auc

In [54]:
# importation des données
Base_logistic = pd.read_csv("/Users/diao028606/Documents/2022/UC/Challenge QoE/Base/V2/table_matrice_challengeQOEV2.csv", header = 0, sep = ";")
Base_logistic.head(20)

,msisdn,coupure,nb_hour_total_coupure,nb_echec,nb_hour_echec,paging_without_response_nb,nb_hour_paging_without_response,nb_call_est,reiter_call_interval_nb,nb_hour_reiter_call,call_est_bad_setupduration_nb,nb_hour_call_est_bad_setupduration,test,Cluster,Cible
0,776707624,48,8,32,5,1,1,53,6,5,1,1,4,2,1
1,785101294,33,6,22,4,0,0,48,1,1,9,6,4,2,1
2,778698304,40,6,26,4,4,4,55,1,1,4,3,4,2,1
3,773644604,54,7,36,5,7,3,38,1,1,30,2,4,2,1
4,776345044,18,6,12,4,4,3,18,2,2,4,4,4,2,1
5,777081164,24,6,16,4,8,6,36,0,0,7,3,4,2,1
6,781051034,36,5,24,3,4,2,41,2,2,12,4,4,2,1
7,779177164,28,7,19,4,4,2,29,2,2,7,5,4,2,1
8,777810834,93,10,62,6,30,8,47,5,5,1,1,4,2,1
9,773353234,76,9,51,6,4,4,79,6,5,3,2,4,2,1
10,771440484,39,5,26,3,17,8,41,4,2,6,1,4,2,1
11,771260544,73,8,49,5,1,1,61,7,6,4,4,4,2,1
12,775671714,63,8,42,5,11,7,66,1,1,5,3,4,2,1
13,772508344,16,4,11,3,16,7,25,1,1,8,5,4,2,1
14,785659884,48,2,32,1,4,3,71,0,0,21,2,4,2,1
15,771357004,28,7,18,4,2,2,30,0,0,14,6,4,2,1
16,784539044,46,7,31,5,22,6,50,2,2,5,3,4,2,1
17,775562844,36,8,24,5,4,4,35,0,0,7,3,4,2,1
18,781564124,29,7,19,5,36,9,22,2,2,4,2,4,2,1
19,775321514,47,6,31,4,2,1,44,5,2,1,1,4,2,1

In [55]:
# description des données
Base_logistic.describe()

,msisdn,coupure,nb_hour_total_coupure,nb_echec,nb_hour_echec,paging_without_response_nb,nb_hour_paging_without_response,nb_call_est,reiter_call_interval_nb,nb_hour_reiter_call,call_est_bad_setupduration_nb,nb_hour_call_est_bad_setupduration,test,Cluster,Cible
count,1.398910e+05,139891.000000,139891.000000,139891.000000,139891.000000,139891.000000,139891.000000,139891.000000,139891.000000,139891.000000,139891.000000,139891.000000,139891.0,139891.000000,139891.000000
mean,7.777101e+08,7.287688,1.262969,4.794905,0.777841,1.610725,0.730676,7.987219,0.706679,0.524301,1.350087,0.609575,4.0,0.331358,0.165679
std,4.687737e+06,17.840549,2.382651,11.865418,1.560058,5.607480,1.681241,20.748730,2.062247,1.007173,4.357133,1.506867,0.0,0.743587,0.371794
min,7.051854e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.0,0.000000,0.000000
25%,7.737677e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.0,0.000000,0.000000
50%,7.771609e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.0,0.000000,0.000000
75%,7.820010e+08,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,4.0,0.000000,0.000000
max,7.864999e+08,791.000000,10.000000,527.000000,6.000000,440.000000,16.000000,1116.000000,268.000000,24.000000,218.000000,13.000000,4.0,2.000000,1.000000

In [56]:
# Separating the independent variables (features) and the dependent variable (target)

columnList = Base_logistic.columns.to_list()
columnList.remove("msisdn")
columnList.remove("Cluster")
columnList.remove("test")
columnList.remove("nb_call_est")
columnList.remove("Cible")
X = pd.DataFrame(Base_logistic.loc[:, columnList])
y = pd.DataFrame(Base_logistic.loc[:, ["Cible"]])

# Splitting the data into training and testing sets (training:testing = 7:3)
(X_train, X_test, y_train, y_test) = train_test_split(X, y, test_size=0.3)
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(97923, 10)
(97923, 1)
(41968, 10)
(41968, 1)

In [58]:
y

        Cible
0           1
1           1
2           1
3           1
4           1
...       ...
139886      0
139887      0
139888      0
139889      0
139890      0

[139891 rows x 1 columns]

In [59]:
# Performing logistic regression analysis and building the classification model

# Creating an instance of the LogisticRegression model with a specified parameter
clf = LogisticRegression(C=1000)

# Fitting the model to the training data
clf.fit(X_train, y_train)

/Users/diao028606/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

LogisticRegression(C=1000)

In [60]:
# Obtaining the coefficients of the classification model

i = 0
for val in columnList:
    if i > 0:
        preStr = " + "
    else:
        preStr = ""
    print(preStr + str(round(clf.coef_[0][i], 4)) + " * " + val)
    i = i + 1
print(" + " + str(clf.intercept_) + " (intercept)")

0.6091 * coupure
 + 1.5249 * nb_hour_total_coupure
 + 0.5874 * nb_echec
 + 1.3891 * nb_hour_echec
 + 0.7623 * paging_without_response_nb
 + 0.8295 * nb_hour_paging_without_response
 + 0.4028 * reiter_call_interval_nb
 + 0.4039 * nb_hour_reiter_call
 + 1.2725 * call_est_bad_setupduration_nb
 + 2.5077 * nb_hour_call_est_bad_setupduration
 + [-34.77664157] (intercept)

In [46]:
# Performing accuracy validation on the training data

print(accuracy_score(y_train, clf.predict(X_train)))

# Creating a confusion matrix for the training data
conf_mtrx_df = pd.DataFrame(confusion_matrix(y_train, clf.predict(X_train).reshape(-1, 1)))
conf_mtrx_df.rename(columns={0: 'Predicted (0)', 1: 'Predicted (1)'}, index={0: 'Target (0)', 1: 'Target (1)'})

1.0

           predict(0)  predict(1)
target(0)       81740           0
target(1)           0       16183

In [47]:
# Performing accuracy validation on the testing data

print(accuracy_score(y_test, clf.predict(X_test)))

# Creating a confusion matrix for the testing data
conf_mtrx_df = pd.DataFrame(confusion_matrix(y_test, clf.predict(X_test).reshape(-1, 1)))
conf_mtrx_df.rename(columns={0: 'Predicted (0)', 1: 'Predicted (1)'}, index={0: 'Target (0)', 1: 'Target (1)'})

1.0

           predict(0)  predict(1)
target(0)       34974           0
target(1)           0        6994

In [50]:
ypb= clf.predict(X_test)

In [51]:
ypb

array([0, 0, 0, ..., 0, 1, 0])

In [32]:
logreg_new = LogisticRegression()
logreg_new.fit(X_train, y_train)

/Users/diao028606/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

LogisticRegression()

In [33]:
ypred = logreg_new.predict(X_test)

In [39]:
ypb= clf.predict_proba(X_test)

ValueError: X has 11 features per sample; expecting 10

In [34]:
from sklearn import metrics
cnf_matrix = metrics.confusion_matrix(y_test, ypred)
cnf_matrix

array([[34964,     0],
       [    0,  7004]])

In [35]:
X_test.shape

(41968, 10)

In [23]:
print(est2.summary())

/Users/diao028606/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)

AttributeError: 'LogisticRegression' object has no attribute 'summary'

In [37]:
clf.predict(X_test)

ValueError: X has 11 features per sample; expecting 10

In [25]:
X_test["PRED"]= ypred

<ipython-input-25-774fc5fe7d4f>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test["PRED"]= ypred